title: The Lounge &mdash; Self-hosted web IRC client
description: "The official website for The Lounge, the self-hosted web IRC client."
baseurl: ""
plugins:
  - jekyll-sitemap
collections:
  docs:
    output: true
