title: Shout &mdash; The self-hosted web IRC client
description: "The official website for the Shout IRC client."
baseurl: ""
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "autolink", "with_toc_data"]
permalink: pretty
collections:
  docs:
    output: true
